export const en = {
  appName: 'SweatLogs',
  tabs: { workout: 'Workout', calendar: 'Calendar', data: 'Data', planner: 'Planner', settings: 'Settings' },
  common: {
    add: 'Add', cancel: 'Cancel', clear: 'Clear', close: 'Close', create: 'Create', creating: 'Creating',
    delete: 'Delete', edit: 'Edit', expand: 'Expand', collapse: 'Collapse', minimize: 'Minimize',
    save: 'Save', saving: 'Saving', search: 'Search', browseAll: 'Browse all', exercises: 'Exercises',
    workouts: 'Workouts', sets: 'sets', set: 'set', loading: 'Loading...', noMatches: 'No matches for that search.',
  },
  workout: {
    templates: 'Workout templates', loadTemplate: 'Load template', title: 'Workout', started: 'Workout started',
    focus: 'Focus:', chooseFocus: 'Choose workout focus', noFocusSelected: 'No focus selected',
    exerciseCount: '{count} exercises', marker: 'Marker:', noMarkersSelected: 'No markers selected', sets: 'Sets',
    addExercise: 'Add exercise', notes: 'Notes', save: 'Save workout', saving: 'Saving workout',
    cancel: 'Cancel workout', clearFocus: 'Clear focus', noFocusAvailable: 'No workout focus available.',
    clearMarkers: 'Clear markers', noMarkersAvailable: 'No exercise markers available.',
    focusDialog: 'Workout focus', markersFor: 'Exercise markers for {name}', untagged: 'Untagged workout',
  },
  planner: {
    createTemplate: 'Create workout template', editTemplate: 'Edit workout template', templateName: 'Template name',
    addExercise: 'Add exercise', saveTemplate: 'Save template', savingTemplate: 'Saving template',
    updateTemplate: 'Update template', updatingTemplate: 'Updating template', cancelEditing: 'Cancel editing',
    savedTemplates: 'Saved templates', noTemplates: 'No workout templates yet.', clearFocus: 'Clear focus',
  },
  settings: {
    language: 'Language', languageDescription: 'Choose the language used by SweatLogs.', english: 'English', finnish: 'Finnish',
    dataBackup: 'Data backup', backupDescription: 'Export a complete database backup or replace local data from a previous backup.',
    exportBackup: 'Export backup', importBackup: 'Import backup', createExercise: 'Create exercise', name: 'Name',
    newExercise: 'New exercise', type: 'Type', createFocus: 'Create workout focus', newFocus: 'New workout focus',
    createMarker: 'Create exercise marker', newMarker: 'New exercise marker', exerciseLibrary: 'Exercise Library',
    loadingExercises: 'Loading exercises...', noExercises: 'No exercises yet.', workoutFocus: 'Workout Focus',
    loadingFocuses: 'Loading workout focus...', noFocuses: 'No workout focus yet.', exerciseMarkers: 'Exercise Markers',
    loadingMarkers: 'Loading exercise markers...', noMarkers: 'No exercise markers yet.',
  },
  data: {
    exercise: 'Exercise', exerciseMarker: 'Exercise marker', workoutFocus: 'Workout focus',
    selectExercise: 'Select an exercise to view previous records.',
    selectMarker: 'Select an exercise marker to list matching exercises.',
    selectFocus: 'Select a workout focus to list matching workouts.', noMarkers: 'No markers', noFocus: 'No focus',
    loadingFor: 'Loading {items} for {name}...', noExerciseRecords: 'No exercises have {name} records yet.',
    noWorkouts: 'No workouts have {name} yet.',
    noRecords: 'No records for {name} yet.', loadingRecords: 'Loading records for {name}...',
    noTaggedRecords: 'No {tag} records for {name} yet.', loadingTaggedRecords: 'Loading {tag} records for {name}...',
  },
  calendar: {
    previous: 'Prev', next: 'Next', loadingHistory: 'Loading history...',
    empty: 'Saved workouts will appear here.', noTags: 'No tags', noWorkoutsOn: 'No workouts on {date}.', selectDay: 'Select a day to view workouts.',
  },
  picker: {
    closeExerciseList: 'Close exercise list', searchExercises: 'Search exercises',
    noExerciseMatches: 'No exercises match that search.', suggestions: '{count} suggestions',
    exercisesAvailable: '{count} exercises available', matches: '{count} matches', allExercises: 'All exercises',
    loadError: 'Start the API to load exercises.', loadingExercises: 'Loading exercises...',
  },
  record: {
    edit: 'Edit {name} record', closeEditor: 'Close exercise record editor', saveChanges: 'Save changes',
    saving: 'Saving record', reps: 'Reps', weight: 'Weight', minutes: 'Min', seconds: 'Sec', kilometers: 'Km',
  },
  chart: {
    loading: 'Loading progress graph...', completeWorkout: 'Complete a workout to see progress here.',
    noTimelineRecords: 'No records in this timeline.', enableLine: 'Enable a line to display the graph.',
    lowerBetter: 'Lower is better', weight: 'Weight', time: 'Time', distance: 'Distance', pace: 'Pace',
    rep: 'rep', reps: 'Reps', bestDuration: 'Best duration', bestReps: 'Best reps', bestDistance: 'Best distance', bestPace: 'Best pace', all: 'All',
  },
  setTypes: { strength: 'Strength', duration: 'Duration', repsOnly: 'Reps only', distance: 'Distance', distanceTime: 'Distance + time' },
  actions: {
    closeList: 'Close {item} list', searchItem: 'Search {item}', browseItems: 'Browse all {items}',
    select: 'Select {name}', delete: 'Delete {name}', edit: 'Edit {name}',
    expand: 'Expand {name}', collapse: 'Collapse {name}', remove: 'Remove {name}', add: 'Add {name}',
    removeFromWorkout: 'Remove {name} from workout', chooseMarkers: 'Choose markers for {name}',
    removeSet: 'Remove set from {name}', addSet: 'Add set to {name}',
    viewExerciseData: 'View data for {name}',
  },
  messages: {
    genericError: 'Something went wrong.', templateDeleted: 'Workout template deleted.', workoutSaved: 'Workout saved.',
    workoutDeleted: 'Workout deleted.', recordUpdated: 'Exercise record updated.', recordDeleted: 'Exercise record deleted.',
    exerciseCreated: 'Exercise created.', focusCreated: 'Workout focus created.', markerCreated: 'Exercise marker created.',
    exerciseDeleted: 'Exercise deleted.', focusDeleted: 'Workout focus deleted.', markerDeleted: 'Exercise marker deleted.',
    backupExported: 'Database backup exported.', backupImported: 'Database backup imported.',
    draftRestored: 'Unfinished workout restored.', templateSaved: 'Workout template saved.', templateUpdated: 'Workout template updated.',
    templateLoaded: '{name} loaded.', workoutCancelled: 'Workout cancelled.', exerciseRemoved: 'Exercise removed.', focusRemoved: 'Workout focus removed.', markerRemoved: 'Exercise marker removed.',
    deleteTemplateTitle: 'Delete template?', deleteTemplateBody: 'Delete {name}?',
    deleteWorkoutTitle: 'Delete workout?', deleteWorkoutBody: 'Delete {name}?',
    deleteRecordTitle: 'Delete exercise record?', deleteRecordBody: 'Delete the {name} record from {date}?',
  },
  dialogs: {
    deleteRecordTitle: 'Delete exercise record?', deleteRecordBody: 'This removes the exercise and all its sets from the completed workout. This cannot be undone.', keepRecord: 'Keep record',
    replaceDataTitle: 'Replace local data?', replaceDataBody: 'Importing a backup replaces all current SweatLogs data on this phone. Export your current database first if you may need it later.', chooseBackup: 'Choose backup',
    cancelWorkoutTitle: 'Cancel workout?', cancelWorkoutBody: 'All exercises, sets, focus selections, and notes in this workout will be cleared.', keepWorkout: 'Keep workout',
    deleteWorkoutBody: 'Delete workout from {date}? This cannot be undone.', deleteExerciseTitle: 'Delete exercise?', deleteExerciseBody: 'Remove {name} from exercise pickers? Past workouts stay unchanged.',
    deleteFocusTitle: 'Delete workout focus?', deleteFocusBody: 'Remove {name} from workout focus pickers? Past workouts stay unchanged.', deleteMarkerTitle: 'Delete exercise marker?', deleteMarkerBody: 'Remove {name} from exercise marker pickers? Past workouts stay unchanged.',
  },
  validation: {
    focusRequired: 'Workout focus is required.', notesLength: 'Workout notes must be 2000 characters or fewer.', maxSets: '{name} can have at most {count} sets.',
    completedSetRequired: 'Add at least one completed set for {name}.', positiveReps: 'Reps must be a positive whole number for {name}.',
    nonnegativeWeight: 'Weight must be zero or more for {name}.', positiveDistance: 'Distance must be a positive number of kilometers for {name}.',
    wholeTime: 'Time must use whole minutes and seconds for {name}.', secondsRange: 'Seconds must be between 0 and 59 for {name}.', positiveTime: 'Time must be greater than zero for {name}.',
  },
  metrics: {
    reps: '{count} reps', minutesSeconds: '{minutes} min {seconds} sec', minutes: '{count} min', seconds: '{count} sec',
  },
} as const;

type WidenStrings<T> = { [K in keyof T]: T[K] extends string ? string : WidenStrings<T[K]> };
export type TranslationTable = WidenStrings<typeof en>;
