import type { TranslationTable } from './en';

export const fi: TranslationTable = {
  appName: 'SweatLogs',
  tabs: { workout: 'Treeni', calendar: 'Kalenteri', data: 'Tiedot', planner: 'Treenipohja', settings: 'Asetukset' },
  common: {
    add: 'Lisää', cancel: 'Peruuta', clear: 'Tyhjennä', close: 'Sulje', create: 'Luo', creating: 'Luodaan', delete: 'Poista',
    edit: 'Muokkaa', expand: 'Laajenna', collapse: 'Pienennä', minimize: 'Pienennä', save: 'Tallenna', saving: 'Tallennetaan',
    search: 'Hae', browseAll: 'Näytä kaikki', exercises: 'Liikkeet', workouts: 'Treenit', sets: 'sarjaa', set: 'sarja',
    loading: 'Ladataan...', noMatches: 'Haulla ei löytynyt tuloksia.',
  },
  workout: {
    templates: 'Treenipohjat', loadTemplate: 'Lataa pohja', title: 'Treeni', started: 'Treeni aloitettu', focus: 'Painotus:',
    chooseFocus: 'Valitse treenin painotus', noFocusSelected: 'Ei valittua painotusta', exerciseCount: '{count} liikettä',
    marker: 'Merkintä:', noMarkersSelected: 'Ei valittuja merkintöjä', sets: 'Sarjat', addExercise: 'Lisää liike', notes: 'Muistiinpanot',
    save: 'Tallenna treeni', saving: 'Tallennetaan treeniä', cancel: 'Peruuta treeni', clearFocus: 'Tyhjennä painotus',
    noFocusAvailable: 'Treenin painotuksia ei ole saatavilla.', clearMarkers: 'Tyhjennä merkinnät',
    noMarkersAvailable: 'Liikemerkintöjä ei ole saatavilla.', focusDialog: 'Treenin painotus',
    markersFor: 'Liikkeen {name} merkinnät', untagged: 'Luokittelematon treeni',
    exerciseInfo: 'Liikkeen tiedot', noExerciseDescription: 'Kuvausta ei ole lisätty.', restTimer: 'Palautumisajastin',
    restComplete: 'Palautumisaika päättyi', restCompleteFor: 'Jatka liikettä {name}.', stopAlarm: 'Pysäytä hälytys',
  },
  planner: {
    createTemplate: 'Luo treenipohja', editTemplate: 'Muokkaa treenipohjaa', templateName: 'Pohjan nimi', addExercise: 'Lisää liike',
    saveTemplate: 'Tallenna pohja', savingTemplate: 'Tallennetaan pohjaa', updateTemplate: 'Päivitä pohja',
    updatingTemplate: 'Päivitetään pohjaa', cancelEditing: 'Peruuta muokkaus', savedTemplates: 'Tallennetut pohjat',
    noTemplates: 'Treenipohjia ei ole vielä.', clearFocus: 'Tyhjennä painotus',
  },
  settings: {
    language: 'Kieli', languageDescription: 'Valitse SweatLogsin käyttämä kieli.', english: 'Englanti', finnish: 'Suomi',
    dataBackup: 'Tietojen varmuuskopiointi', backupDescription: 'Luo harjoitustietokannasta varmuuskopio tai korvaa nykyisettiedot aijemmalla varmuuskopiolla.',
    exportBackup: 'Luo varmuuskopio', importBackup: 'Avaa varmuuskopio', createExercise: 'Luo liike', name: 'Nimi',
    newExercise: 'Uusi liike', editExercise: 'Muokkaa liikettä', saveExerciseChanges: 'Tallenna muutokset', exerciseTypeLocked: 'Liikkeen tyyppiä ei voi muuttaa luomisen jälkeen.', description: 'Kuvaus', exerciseDescriptionPlaceholder: 'Ohjeet tai viitelinkki', type: 'Tyyppi', createFocus: 'Luo treenin painotus', newFocus: 'Uusi treenin painotus',
    createMarker: 'Luo liikemerkintä', newMarker: 'Uusi liikemerkintä', exerciseLibrary: 'Liikekirjasto',
    loadingExercises: 'Ladataan liikkeitä...', noExercises: 'Liikkeitä ei ole vielä.', workoutFocus: 'Treenin painotus',
    loadingFocuses: 'Ladataan painotuksia...', noFocuses: 'Treenin painotuksia ei ole vielä.', exerciseMarkers: 'Liikemerkinnät',
    loadingMarkers: 'Ladataan liikemerkintöjä...', noMarkers: 'Liikemerkintöjä ei ole vielä.',
  },
  data: {
    exercise: 'Liike', exerciseMarker: 'Liikemerkintä', workoutFocus: 'Treenin painotus',
    selectExercise: 'Valitse liike nähdäksesi aiemmat tulokset.', selectMarker: 'Valitse liikemerkintä nähdäksesi vastaavat liikkeet.',
    selectFocus: 'Valitse treenin painotus nähdäksesi vastaavat treenit.', noMarkers: 'Ei merkintöjä', noFocus: 'Ei painotusta',
    loadingFor: 'Ladataan {items}: {name}...', noExerciseRecords: 'Merkinnällä {name} ei ole vielä liiketuloksia.',
    noWorkouts: 'Painotuksella {name} ei ole vielä treenejä.',
    noRecords: 'Liikkeellä {name} ei ole vielä tuloksia.', loadingRecords: 'Ladataan liikkeen {name} tuloksia...',
    noTaggedRecords: 'Liikkeellä {name} ei ole vielä tuloksia merkinnällä {tag}.', loadingTaggedRecords: 'Ladataan liikkeen {name} tuloksia merkinnällä {tag}...',
  },
  calendar: { previous: 'Edellinen', next: 'Seuraava', loadingHistory: 'Ladataan historiaa...', empty: 'Tallennetut treenit näkyvät täällä.', noTags: 'Ei tunnisteita', noWorkoutsOn: 'Päivällä {date} ei ole treenejä.', selectDay: 'Valitse päivä nähdäksesi treenit.' },
  picker: {
    closeExerciseList: 'Sulje liikelista', searchExercises: 'Hae liikkeitä', noExerciseMatches: 'Haulla ei löytynyt liikkeitä.',
    suggestions: '{count} ehdotusta', exercisesAvailable: '{count} liikettä saatavilla', matches: '{count} osumaa',
    allExercises: 'Kaikki liikkeet', loadError: 'Käynnistä API ladataksesi liikkeet.', loadingExercises: 'Ladataan liikkeitä...',
  },
  record: {
    edit: 'Muokkaa tulosta: {name}', closeEditor: 'Sulje liiketuloksen muokkaus', saveChanges: 'Tallenna muutokset',
    saving: 'Tallennetaan tulosta', reps: 'Toistot', weight: 'Paino', minutes: 'Min', seconds: 'Sek', kilometers: 'Km',
  },
  chart: {
    loading: 'Ladataan kehityskäyrää...', completeWorkout: 'Tee treeni nähdäksesi kehityksen.', noTimelineRecords: 'Aikavälillä ei ole tuloksia.',
    enableLine: 'Ota viiva käyttöön nähdäksesi kuvaajan.', lowerBetter: 'Pienempi on parempi', weight: 'Paino', time: 'Aika',
    distance: 'Matka', pace: 'Vauhti', rep: 'toisto', reps: 'Toistot', bestDuration: 'Paras kesto', bestReps: 'Parhaat toistot',
    bestDistance: 'Paras matka', bestPace: 'Paras vauhti', all: 'Kaikki',
  },
  setTypes: { strength: 'Voima', duration: 'Kesto', repsOnly: 'Vain toistot', distance: 'Matka', distanceTime: 'Matka + aika' },
  actions: {
    closeList: 'Sulje lista: {item}', searchItem: 'Hae: {item}', browseItems: 'Näytä kaikki: {items}', select: 'Valitse {name}',
    delete: 'Poista {name}', edit: 'Muokkaa {name}', expand: 'Laajenna {name}', collapse: 'Pienennä {name}', remove: 'Poista {name}',
    add: 'Lisää {name}', removeFromWorkout: 'Poista {name} treenistä', chooseMarkers: 'Valitse merkinnät liikkeelle {name}',
    removeSet: 'Poista sarja liikkeestä {name}', addSet: 'Lisää sarja liikkeeseen {name}',
    viewExerciseData: 'Näytä liikkeen {name} tiedot',
    setRestTimer: 'Aseta liikkeen {name} palautumisaika', startRestTimer: 'Käynnistä liikkeen {name} palautumisajastin', pauseRestTimer: 'Keskeytä liikkeen {name} palautumisajastin', resetRestTimer: 'Nollaa liikkeen {name} palautumisajastin',
  },
  messages: {
    genericError: 'Jokin meni vikaan.', templateDeleted: 'Treenipohja poistettu.', workoutSaved: 'Treeni tallennettu.',
    workoutDeleted: 'Treeni poistettu.', recordUpdated: 'Liiketulos päivitetty.', recordDeleted: 'Liiketulos poistettu.',
    exerciseCreated: 'Liike luotu.', exerciseUpdated: 'Liike päivitetty.', focusCreated: 'Treenin painotus luotu.', markerCreated: 'Liikemerkintä luotu.',
    exerciseDeleted: 'Liike poistettu.', focusDeleted: 'Treenin painotus poistettu.', markerDeleted: 'Liikemerkintä poistettu.',
    backupExported: 'Tietokannan varmuuskopio viety.', backupImported: 'Tietokannan varmuuskopio tuotu.',
    draftRestored: 'Keskeneräinen treeni palautettu.', templateSaved: 'Treenipohja tallennettu.', templateUpdated: 'Treenipohja päivitetty.',
    templateLoaded: '{name} ladattu.', workoutCancelled: 'Treeni peruutettu.', exerciseRemoved: 'Liike poistettu.', focusRemoved: 'Treenin painotus poistettu.', markerRemoved: 'Liikemerkintä poistettu.',
    deleteTemplateTitle: 'Poistetaanko pohja?', deleteTemplateBody: 'Poistetaanko {name}?', deleteWorkoutTitle: 'Poistetaanko treeni?',
    deleteWorkoutBody: 'Poistetaanko {name}?', deleteRecordTitle: 'Poistetaanko liiketulos?', deleteRecordBody: 'Poistetaanko liikkeen {name} tulos päivältä {date}?',
  },
  dialogs: {
    deleteRecordTitle: 'Poistetaanko liiketulos?', deleteRecordBody: 'Tämä poistaa liikkeen ja kaikki sen sarjat valmiista treenistä. Toimintoa ei voi kumota.', keepRecord: 'Säilytä tulos',
    replaceDataTitle: 'Korvataanko paikalliset tiedot?', replaceDataBody: 'Varmuuskopion tuonti korvaa kaikki tämän puhelimen nykyiset SweatLogs-tiedot. Vie nykyinen tietokanta ensin, jos saatat tarvita sitä myöhemmin.', chooseBackup: 'Valitse varmuuskopio',
    cancelWorkoutTitle: 'Peruutetaanko treeni?', cancelWorkoutBody: 'Kaikki tämän treenin liikkeet, sarjat, painotukset ja muistiinpanot tyhjennetään.', keepWorkout: 'Säilytä treeni',
    deleteWorkoutBody: 'Poistetaanko treeni päivältä {date}? Toimintoa ei voi kumota.', deleteExerciseTitle: 'Poistetaanko liike?', deleteExerciseBody: 'Poistetaanko {name} liikevalinnoista? Aiemmat treenit säilyvät ennallaan.',
    deleteFocusTitle: 'Poistetaanko treenin painotus?', deleteFocusBody: 'Poistetaanko {name} painotusvalinnoista? Aiemmat treenit säilyvät ennallaan.', deleteMarkerTitle: 'Poistetaanko liikemerkintä?', deleteMarkerBody: 'Poistetaanko {name} merkintävalinnoista? Aiemmat treenit säilyvät ennallaan.',
  },
  validation: {
    focusRequired: 'Treenin painotus on pakollinen.', notesLength: 'Treenin muistiinpanot saavat olla enintään 2000 merkkiä.', maxSets: 'Liikkeellä {name} voi olla enintään {count} sarjaa.',
    completedSetRequired: 'Lisää vähintään yksi valmis sarja liikkeelle {name}.', positiveReps: 'Toistojen on oltava positiivinen kokonaisluku liikkeelle {name}.',
    nonnegativeWeight: 'Painon on oltava vähintään nolla liikkeelle {name}.', positiveDistance: 'Matkan on oltava positiivinen kilometrimäärä liikkeelle {name}.',
    wholeTime: 'Ajan minuuttien ja sekuntien on oltava kokonaislukuja liikkeelle {name}.', secondsRange: 'Sekuntien on oltava 0–59 liikkeelle {name}.', positiveTime: 'Ajan on oltava suurempi kuin nolla liikkeelle {name}.',
  },
  metrics: {
    reps: '{count} toistoa', minutesSeconds: '{minutes} min {seconds} s', minutes: '{count} min', seconds: '{count} s',
  },
};
