import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F7F7F2',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 40,
    gap: 18,
  },
  header: {
    paddingHorizontal: 20,
  },
  headerTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  headerTitleBlock: {
    flex: 1,
    gap: 4,
  },
  splashScreen: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    flex: 1,
    justifyContent: 'center',
  },
  splashTitle: {
    color: '#214E3A',
    fontSize: 42,
    fontWeight: '800',
  },
  notice: {
    backgroundColor: '#EAF4EC',
    borderColor: '#BAD8C2',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  noticeSlot: {
    minHeight: 34,
  },
  noticeError: {
    backgroundColor: '#FDEDE8',
    borderColor: '#E7B7A8',
  },
  noticeText: {
    color: '#214E3A',
    fontSize: 14,
    fontWeight: '700',
  },
  noticeTextError: {
    color: '#8B2D1E',
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
    gap: 14,
  },
  loginScreen: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  loginCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D9DED7',
    borderRadius: 18,
    borderWidth: 1,
    gap: 20,
    maxWidth: 420,
    paddingHorizontal: 28,
    paddingVertical: 36,
    width: '100%',
  },
  loginTitle: {
    color: '#214E3A',
    fontSize: 40,
    fontWeight: '800',
  },
  loginSubtitle: {
    color: '#54635A',
    fontSize: 16,
    lineHeight: 23,
    textAlign: 'center',
  },
  loginStatusText: {
    color: '#54635A',
    fontSize: 15,
    marginTop: 14,
  },
  loginErrorText: {
    color: '#B4462E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  accountName: {
    color: '#202522',
    fontSize: 17,
    fontWeight: '800',
  },
  accountEmail: {
    color: '#6F7A73',
    fontSize: 14,
  },
  signOutButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: '#E3B8AE',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  signOutButtonText: {
    color: '#B4462E',
    fontSize: 15,
    fontWeight: '800',
  },
  activeWorkoutSection: {
    backgroundColor: '#EAF7EE',
    borderColor: '#9CC8A8',
    borderWidth: 1,
  },
  activeWorkoutHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  activeWorkoutIndicator: {
    alignItems: 'center',
    backgroundColor: '#D5EEDD',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  activeWorkoutIndicatorDot: {
    backgroundColor: '#2E7D4A',
    borderRadius: 5,
    height: 9,
    width: 9,
  },
  activeWorkoutIndicatorText: {
    color: '#214E3A',
    fontSize: 12,
    fontWeight: '800',
  },
  sectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#202522',
    fontSize: 18,
    fontWeight: '700',
  },
  databaseBackupDescription: {
    color: '#54635A',
    fontSize: 14,
    lineHeight: 20,
  },
  databaseBackupActions: {
    flexDirection: 'row',
    gap: 10,
  },
  databaseBackupButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2F8',
    borderColor: '#B8CEE0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 10,
  },
  databaseBackupButtonText: {
    color: '#215F9A',
    fontSize: 14,
    fontWeight: '800',
  },
  dataModeRow: {
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  dataModeButton: {
    alignItems: 'center',
    borderRadius: 6,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 6,
  },
  dataModeButtonSelected: {
    backgroundColor: '#214E3A',
  },
  dataModeButtonText: {
    color: '#54635A',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  dataModeButtonTextSelected: {
    color: '#FFFFFF',
  },
  dataSelectedTitleBlock: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  workoutTagRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  tagRowLabel: {
    color: '#202522',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
  },

  workoutTagChipList: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minHeight: 32,
  },
  workoutTagPlaceholder: {
	paddingVertical: 6,
    color: '#6F7A73',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 20,
  },
  workoutTagPlaceholderCentered: {
    flex: 1,
    textAlign: 'center',
  },
  workoutTagChip: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 30,
    paddingHorizontal: 8,
  },
  workoutTagChipText: {
    color: '#202522',
    fontSize: 13,
    fontWeight: '800',
  },
  workoutTagSwatch: {
    borderColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    height: 12,
    width: 12,
  },
  workoutTagPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  workoutTagOption: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  workoutTagOptionSelected: {
    backgroundColor: '#EAF4EC',
    borderColor: '#214E3A',
  },
  workoutTagOptionText: {
    color: '#202522',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  workoutTagColorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  workoutTagColorOption: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  workoutTagColorOptionSelected: {
    backgroundColor: '#EAF4EC',
    borderColor: '#214E3A',
  },
  workoutTagColorSwatch: {
    borderColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    height: 18,
    width: 18,
  },
  exerciseCount: {
    color: '#54635A',
    fontSize: 13,
    fontWeight: '700',
  },
  exerciseSearchInput: {
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1B1E1C',
    fontSize: 16,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  addExercisePickerButton: {
    alignItems: 'center',
    backgroundColor: '#D56A3A',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  addExercisePickerButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  exercisePickerHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exercisePickerTitle: {
    color: '#202522',
    fontSize: 15,
    fontWeight: '800',
  },
  exercisePickerMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  exercisePickerStatus: {
    color: '#54635A',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  exercisePickerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  exercisePickerActionText: {
    color: '#215F9A',
    fontSize: 13,
    fontWeight: '800',
  },
  exerciseList: {
    gap: 8,
  },
  exerciseOption: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  exerciseOptionText: {
    color: '#202522',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
  },
  exerciseDialogOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(27, 30, 28, 0.36)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  exerciseDialog: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    maxHeight: '78%',
    padding: 14,
    width: '100%',
  },
  exerciseDialogHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exerciseDialogTitle: {
    color: '#202522',
    fontSize: 17,
    fontWeight: '800',
  },
  exerciseDialogCloseButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  exerciseDialogList: {
    flexGrow: 0,
  },
  exerciseDialogListContent: {
    gap: 8,
    paddingBottom: 2,
  },
  addExerciseRow: {
    flexDirection: 'row',
    gap: 10,
  },
  exerciseSetTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  languageOptionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  languageOption: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  languageOptionText: {
    color: '#54635A',
    fontSize: 12,
    fontWeight: '800',
  },
  exerciseCreatorControlLabel: {
    color: '#202522',
    fontSize: 14,
    fontWeight: '800',
  },
  createExerciseButton: {
    alignSelf: 'stretch',
  },
  exerciseSetTypeOption: {
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 10,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 10,
    minHeight: 92,
    padding: 10,
  },
  exerciseSetTypeOptionSelected: {
    backgroundColor: '#EAF4EC',
    borderColor: '#214E3A',
  },
  exerciseSetTypeOptionText: {
    color: '#54635A',
    fontSize: 12,
    fontWeight: '800',
  },
  exerciseSetTypeOptionTextSelected: {
    color: '#214E3A',
  },
  exerciseSetTypeOptionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exerciseSetTypePreview: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 5,
  },
  exerciseSetTypeSetNumber: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#6F7A73',
    borderRadius: 6,
    justifyContent: 'center',
    minWidth: 22,
  },
  exerciseSetTypeSetNumberSelected: {
    backgroundColor: '#214E3A',
  },
  exerciseSetTypeSetNumberText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  exerciseSetTypeFieldPreview: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8DED4',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    gap: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 4,
  },
  exerciseSetTypeFieldPreviewSelected: {
    backgroundColor: '#F4FAF5',
    borderColor: '#9CC8A8',
  },
  exerciseSetTypeFieldOrder: {
    color: '#8A948E',
    fontSize: 9,
    fontWeight: '800',
  },
  exerciseSetTypeFieldText: {
    color: '#54635A',
    fontSize: 10,
    fontWeight: '800',
  },
  exerciseInput: {
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1B1E1C',
    flex: 1,
    fontSize: 16,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#D56A3A',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 18,
  },
  actionButtonDisabled: {
    backgroundColor: '#9AA59E',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  settingsExerciseDeleteButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  workoutExercise: {
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  workoutExerciseHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  workoutExerciseTagRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  exerciseTagChipList: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minHeight: 30,
  },
  workoutExerciseHeaderButton: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  workoutExerciseTitleBlock: {
    flex: 1,
    gap: 3,
  },
  workoutExerciseTitle: {
    color: '#202522',
    fontSize: 17,
    fontWeight: '800',
  },
  workoutExerciseDeleteButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  setRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  setNumber: {
    backgroundColor: '#202522',
    borderRadius: 8,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    overflow: 'hidden',
    paddingVertical: 11,
    textAlign: 'center',
    width: 44,
  },
  inputGroup: {
    flex: 1,
    gap: 5,
  },
  inputLabel: {
    color: '#54635A',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  numberInput: {
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1B1E1C',
    fontSize: 17,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  exerciseFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  setControlLabel: {
    color: '#202522',
    fontSize: 15,
    fontWeight: '800',
  },
  setStepper: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  setStepperButton: {
    alignItems: 'center',
    backgroundColor: '#EFF2EB',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  setStepperButtonDisabled: {
    backgroundColor: '#F7F7F2',
    borderColor: '#E0E4DD',
  },
  setStepperCount: {
    color: '#202522',
    fontSize: 15,
    fontWeight: '800',
    minWidth: 24,
    textAlign: 'center',
  },
  workoutNotesInput: {
    backgroundColor: '#F7F7F2',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1B1E1C',
    fontSize: 16,
    minHeight: 92,
    padding: 12,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#214E3A',
    borderRadius: 8,
    minHeight: 50,
    justifyContent: 'center',
  },
  saveButtonDisabled: {
    backgroundColor: '#9AA59E',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  cancelWorkoutButton: {
    alignItems: 'center',
    borderColor: '#B4462E',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 16,
  },
  cancelWorkoutButtonText: {
    color: '#B4462E',
    fontSize: 15,
    fontWeight: '800',
  },
  exerciseOptionTitleBlock: {
    flex: 1,
  },
  emptyText: {
    color: '#6F7A73',
    fontSize: 15,
  },
  calendarHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  calendarTitle: {
    color: '#202522',
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
  },
  calendarNavButton: {
    alignItems: 'center',
    backgroundColor: '#EFF2EB',
    borderColor: '#D8DED4',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    minWidth: 58,
    paddingHorizontal: 10,
  },
  calendarNavText: {
    color: '#215F9A',
    fontSize: 13,
    fontWeight: '800',
  },
  calendarWeekRow: {
    flexDirection: 'row',
  },
  calendarWeekday: {
    color: '#54635A',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarCell: {
    aspectRatio: 1,
    padding: 3,
    width: '14.2857%',
  },
  calendarDay: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
  },
  calendarDayMuted: {
    backgroundColor: '#FAFAF7',
    borderColor: '#ECEFEB',
  },
  calendarDayWithWorkout: {
    borderColor: '#D56A3A',
  },
  calendarDaySelected: {
    backgroundColor: '#214E3A',
    borderColor: '#214E3A',
  },
  calendarDayText: {
    color: '#202522',
    fontSize: 14,
    fontWeight: '800',
  },
  calendarDayTextMuted: {
    color: '#A1AAA4',
  },
  calendarDayTextSelected: {
    color: '#FFFFFF',
  },
  calendarWorkoutDots: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    justifyContent: 'center',
    marginTop: 4,
    maxWidth: 38,
  },
  calendarWorkoutDot: {
    backgroundColor: '#214E3A',
    borderColor: '#FFFFFF',
    borderRadius: 4,
    borderWidth: 1,
    height: 8,
    width: 8,
  },
  calendarWorkoutDotSelected: {
    borderColor: '#FFFFFF',
  },
  historyItem: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  historyHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  historyHeaderButton: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  historyTitleBlock: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minHeight: 36,
  },
  historyColorIndicator: {
    borderColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    height: 12,
    width: 12,
  },
  historyDeleteButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  historyDeleteButtonDisabled: {
    opacity: 0.5,
  },
  historyTitle: {
    color: '#202522',
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
  },
  historyNotes: {
    backgroundColor: '#F7F7F2',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    color: '#38423C',
    fontSize: 14,
    lineHeight: 20,
    padding: 10,
  },
  historyExerciseList: {
    borderTopColor: '#E0E4DD',
    borderTopWidth: 1,
    gap: 12,
    paddingTop: 10,
  },
  historyExerciseBlock: {
    gap: 8,
  },
  historyExerciseRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  historyExerciseTitleBlock: {
    flex: 1,
    gap: 6,
  },
  historyExerciseTagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  historyExerciseName: {
    color: '#202522',
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
  },
  historySetList: {
    gap: 6,
  },
  historySetRow: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  historySetNumber: {
    backgroundColor: '#202522',
    borderRadius: 6,
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    minWidth: 26,
    overflow: 'hidden',
    paddingVertical: 4,
    textAlign: 'center',
  },
  historySetMetric: {
    color: '#38423C',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  dataRecordDate: {
    color: '#202522',
    fontSize: 15,
    fontWeight: '800',
  },
  progressChart: {
    backgroundColor: '#F9FBF9',
    borderColor: '#E0E6E1',
    borderRadius: 10,
    borderWidth: 1,
    overflow: 'hidden',
    paddingTop: 10,
  },
  progressChartEmpty: {
    alignItems: 'center',
    backgroundColor: '#F9FBF9',
    borderColor: '#E0E6E1',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 180,
    padding: 20,
  },
  progressChartHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  progressChartTimeline: {
    alignSelf: 'center',
    backgroundColor: '#E9EEEA',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 3,
    marginBottom: 8,
    padding: 3,
  },
  progressChartTimelineButton: {
    borderRadius: 6,
    minWidth: 42,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  progressChartTimelineButtonSelected: {
    backgroundColor: '#FFFFFF',
  },
  progressChartTimelineText: {
    color: '#6F7A73',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  progressChartTimelineTextSelected: {
    color: '#214E3A',
  },
  progressChartAxisLabel: {
    color: '#202522',
    fontSize: 13,
    fontWeight: '800',
  },
  progressChartHint: {
    color: '#6F7A73',
    fontSize: 11,
    fontWeight: '700',
  },
  progressChartLegend: {
    borderTopColor: '#E0E6E1',
    borderTopWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    padding: 10,
  },
  progressChartLegendItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  progressChartLegendItemHidden: {
    opacity: 0.35,
  },
  progressChartLegendColor: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  progressChartLegendText: {
    color: '#54635A',
    fontSize: 11,
    fontWeight: '700',
  },
  progressChartEmptyContent: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 150,
    padding: 20,
  },
  plannerTagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  plannerExerciseList: {
    gap: 8,
  },
  plannerExerciseRow: {
    alignItems: 'center',
    backgroundColor: '#F7F7F2',
    borderColor: '#E0E4DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  plannerExerciseOrder: {
    color: '#215F9A',
    fontSize: 14,
    fontWeight: '800',
  },
  plannerExerciseName: {
    color: '#202522',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
  },
  plannerSetCountControl: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  plannerSetCountButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2F8',
    borderRadius: 7,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  plannerSetCountText: {
    color: '#38423C',
    fontSize: 13,
    fontWeight: '700',
    minWidth: 42,
    textAlign: 'center',
  },
  plannerTemplateCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D9DED7',
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  plannerTemplateHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  plannerTemplateExpandButton: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
  },
  plannerTemplateActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  plannerTemplateTitleBlock: {
    flex: 1,
    gap: 2,
  },
  plannerTemplateTitle: {
    color: '#202522',
    fontSize: 17,
    fontWeight: '800',
  },
  plannerTemplateMeta: {
    color: '#6F7A73',
    fontSize: 13,
  },
  plannerTemplateExercises: {
    color: '#38423C',
    fontSize: 14,
    lineHeight: 20,
  },
  plannerSavedSetCount: {
    backgroundColor: '#EAF2F8',
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  workoutTemplateBlock: {
    gap: 6,
  },
  workoutTemplateLabel: {
    color: '#6F7A73',
    fontSize: 13,
    fontWeight: '700',
  },
  workoutTemplateList: {
    gap: 8,
  },
  workoutTemplateButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2F8',
    borderColor: '#B8CEE0',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  workoutTemplateButtonText: {
    color: '#215F9A',
    fontSize: 14,
    fontWeight: '800',
  },
});
